### ISSUE TITLE
Fail to let bot join because fail to get GetMeetingInfoData

### ISSUE THREAD

**Issue by tchen0915** [RealKeyboardWarrior/zoomer#6]
First of all, really appreciated the impressive work you did.
I am trying to set up bot to join the zoom meeting and do the audio/video recording.
I tried both main and audio branch. However, I fail to let bot join the meeting due to http get request failure in GetMeetingInfoData function

`$ go run examples/record-video/videorecoder.go`
`panic: Get "https:///wc/ping/?ts=0&auth=&rwcToken=&dmz=1": http: no Host in request URL`

I had a live zoom session and used the right meeting number, meeting password, client id as api key ad client secret as api secret. This works in the Chris's master branch.

Could you help me with this?

**Comment by RealKeyboardWarrior** [comment]
Should work now, see #7.
